#!/usr/bin/env python3
"""GitHub Repo Analyzer - Find contribution opportunities."""

import argparse
import json
import os
import sys
from datetime import datetime, timedelta
from urllib.request import urlopen, Request
from urllib.parse import urlencode

GITHUB_API = "https://api.github.com"


def api_request(endpoint, params=None):
    """Make a GitHub API request."""
    url = f"{GITHUB_API}{endpoint}"
    if params:
        url += "?" + urlencode(params)
    
    req = Request(url)
    req.add_header("Accept", "application/vnd.github.v3+json")
    req.add_header("User-Agent", "github-repo-analyzer")
    
    # Use token if available
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        req.add_header("Authorization", f"token {token}")
    
    try:
        with urlopen(req, timeout=15) as resp:
            return json.loads(resp.read().decode())
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return None


def search_issues(label="good first issue", language=None, days=30, min_stars=100):
    """Search for issues with given label."""
    since = (datetime.now() - timedelta(days=days)).strftime("%Y-%m-%d")
    query = f'label:"{label}" state:open created:>{since}'
    if language:
        query += f" language:{language}"
    
    data = api_request("/search/issues", {
        "q": query, 
        "sort": "created", 
        "order": "desc", 
        "per_page": 20
    })
    
    if not data:
        return []
    
    issues = []
    for item in data.get("items", [])[:20]:
        repo_url = item.get("repository_url", "")
        parts = repo_url.split("/")
        repo = f"{parts[-2]}/{parts[-1]}" if len(parts) >= 2 else "unknown"
        
        # Calculate difficulty estimate
        body = item.get("body", "") or ""
        difficulty = estimate_difficulty(item.get("title", ""), body)
        
        issues.append({
            "repo": repo,
            "number": item.get("number"),
            "title": item.get("title", ""),
            "url": item.get("html_url"),
            "created": item.get("created_at", "")[:10],
            "difficulty": difficulty,
            "comments": item.get("comments", 0),
        })
    return issues


def estimate_difficulty(title, body):
    """Estimate issue difficulty based on keywords."""
    text = (title + " " + body).lower()
    
    easy_keywords = ["typo", "fix", "update", "doc", "readme", "link", "spelling", "grammar"]
    hard_keywords = ["refactor", "architecture", "redesign", "implement", "feature", "add support"]
    
    easy_score = sum(1 for k in easy_keywords if k in text)
    hard_score = sum(1 for k in hard_keywords if k in text)
    
    if easy_score > hard_score:
        return "🟢 Easy"
    elif hard_score > easy_score:
        return "🔴 Hard"
    return "🟡 Medium"


def generate_markdown(issues, language=None):
    """Generate a markdown report."""
    lines = [
        "# 🎯 Good First Issues Report",
        f"\nGenerated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"\n## Filter: Language={language or 'All'}, Last 30 days\n"
    ]
    
    if not issues:
        lines.append("No issues found. Try adjusting filters.")
        return "\n".join(lines)
    
    # Group by difficulty
    easy = [i for i in issues if "Easy" in i["difficulty"]]
    medium = [i for i in issues if "Medium" in i["difficulty"]]
    hard = [i for i in issues if "Hard" in i["difficulty"]]
    
    for diff_name, diff_issues in [("🟢 Easy", easy), ("🟡 Medium", medium), ("🔴 Hard", hard)]:
        if diff_issues:
            lines.append(f"\n### {diff_name} ({len(diff_issues)} issues)\n")
            for issue in diff_issues[:5]:
                lines.append(f"- **[{issue['repo']}#{issue['number']}]({issue['url']})**")
                lines.append(f"  - {issue['title']}")
                lines.append(f"  - 💬 {issue['comments']} comments | 📅 {issue['created']}")
                lines.append("")
    
    lines.extend([
        "---",
        "\n*Generated by [github-repo-analyzer](https://github.com/crazybird/github-repo-analyzer)*",
        "\n**Support this tool:** ETH `0xE1854bE3A859F1B9B40814d9711E7d5d2cFE9C80`"
    ])
    
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="GitHub Repo Analyzer")
    subparsers = parser.add_subparsers(dest="command")
    
    search_parser = subparsers.add_parser("search", help="Search for issues")
    search_parser.add_argument("--label", default="good first issue", help="Issue label")
    search_parser.add_argument("--language", help="Programming language")
    search_parser.add_argument("--days", type=int, default=30, help="Days since creation")
    search_parser.add_argument("--output", "-o", help="Output file (markdown)")
    
    args = parser.parse_args()
    
    if args.command == "search":
        print(f"🔍 Searching for '{args.label}' issues...")
        issues = search_issues(args.label, args.language, args.days)
        
        if issues:
            print(f"✅ Found {len(issues)} issues\n")
            
            # Print summary
            for issue in issues[:10]:
                print(f"{issue['difficulty']} | {issue['repo']}#{issue['number']}")
                print(f"  {issue['title'][:70]}")
                print(f"  → {issue['url']}\n")
            
            # Generate markdown if output specified
            if args.output:
                md = generate_markdown(issues, args.language)
                with open(args.output, 'w') as f:
                    f.write(md)
                print(f"📄 Markdown report saved to {args.output}")
        else:
            print("❌ No issues found.")
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
